version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: procrastigo_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: procrastigo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d procrastigo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: procrastigo_backend
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: procrastigo_db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
    command: /app/main

volumes:
  postgres_data: