server:
  port: 8080
  host: "0.0.0.0"

database:
  file: "data/excuses.json"

rate_limiting:
  requests_per_minute: 100

logging:
  level: "info"
  file: "logs/procrastigo.log"

features:
  enable_metrics: true
  enable_swagger: true
  cache_timeout: "5m"